### ISSUE TITLE
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  sorry, too many clients already

### ISSUE THREAD

**Issue by eeokee** [Aurora-Admin-Panel/deploy#10]
问题描述：
数据库连接数太多。
使用docker-compose跑了几天，今天发现页面报错，日志上显示连接数过多。

![image](https://user-images.githubusercontent.com/3079825/106076636-e7d67d80-614a-11eb-9970-6f81e2e0772a.png)

日志：

nginx_1     | 192.168.1.111 - - [28/Jan/2021:01:26:13 +0000] "GET /api/v1/servers/1/ports HTTP/1.1" 500 21 "http://192.168.1.189:8000/app/servers/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "-"
backend_1   | ERROR:    Exception in ASGI application
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
backend_1   |     result = await app(self.scope, self.receive, self.send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
backend_1   |     return await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
backend_1   |     await super().__call__(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
backend_1   |     await self.middleware_stack(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend_1   |     raise exc from None
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend_1   |     await self.app(scope, receive, _send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
backend_1   |     response = await self.dispatch_func(request, self.call_next)
backend_1   |   File "/app/app/main.py", line 70, in db_session_middleware
backend_1   |     response = await call_next(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
backend_1   |     task.result()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
backend_1   |     response = await self.dispatch_func(request, self.call_next)
backend_1   |   File "/app/app/main.py", line 64, in sentry_exception
backend_1   |     raise e
backend_1   |   File "/app/app/main.py", line 56, in sentry_exception
backend_1   |     response = await call_next(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
backend_1   |     task.result()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
backend_1   |     raise exc from None
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
backend_1   |     await self.app(scope, receive, sender)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
backend_1   |     await route.handle(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
backend_1   |     response = await func(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 172, in app
backend_1   |     solved_result = await solve_dependencies(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 518, in solve_dependencies
backend_1   |     solved_result = await solve_dependencies(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 550, in solve_dependencies
backend_1   |     solved = await call(**sub_values)
backend_1   |   File "/app/app/core/auth.py", line 31, in get_current_user
backend_1   |     user = get_user_by_email(db, token_data.email)
backend_1   |   File "/app/app/db/crud/user.py", line 33, in get_user_by_email
backend_1   |     return db.query(User).filter(User.email == email).first()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3402, in first
backend_1   |     ret = list(self[0:1])
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
backend_1   |     return list(res)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
backend_1   |     return self._execute_and_instances(context)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3529, in _execute_and_instances
backend_1   |     conn = self._get_bind_args(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3544, in _get_bind_args
backend_1   |     return fn(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3523, in _connection_from_session
backend_1   |     conn = self.session.connection(**kw)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1138, in connection
backend_1   |     return self._connection_for_bind(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1146, in _connection_for_bind
backend_1   |     return self.transaction._connection_for_bind(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
backend_1   |     conn = bind._contextual_connect()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2304, in _contextual_connect
backend_1   |     self._wrap_pool_connect(self.pool.connect, None),
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2341, in _wrap_pool_connect
backend_1   |     Connection._handle_dbapi_exception_noconnection(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
backend_1   |     util.raise_(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
backend_1   |     raise exception
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
backend_1   |     return fn()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
backend_1   |     return _ConnectionFairy._checkout(self)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
backend_1   |     fairy = _ConnectionRecord.checkout(pool)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
backend_1   |     rec = pool._do_get()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
backend_1   |     self._dec_overflow()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
backend_1   |     compat.raise_(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
backend_1   |     raise exception
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
backend_1   |     return self._create_connection()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
backend_1   |     return _ConnectionRecord(self)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
backend_1   |     self.__connect(first_connect_check=True)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
backend_1   |     pool.logger.debug("Error on connect(): %s", e)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
backend_1   |     compat.raise_(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
backend_1   |     raise exception
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
backend_1   |     connection = pool._invoke_creator(self)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
backend_1   |     return dialect.connect(*cargs, **cparams)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
backend_1   |     return self.dbapi.connect(*cargs, **cparams)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
backend_1   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
backend_1   | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  sorry, too many clients already
backend_1   | 
backend_1   | (Background on this error at: http://sqlalche.me/e/13/e3q8)
nginx_1     | 192.168.1.111 - - [28/Jan/2021:01:26:18 +0000] "GET /app/servers/1 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "-"
nginx_1     | 192.168.1.111 - - [28/Jan/2021:01:26:18 +0000] "GET /static/css/main.81158702.chunk.css HTTP/1.1" 304 0 "http://192.168.1.189:8000/app/servers/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "-"
nginx_1     | 192.168.1.111 - - [28/Jan/2021:01:26:18 +0000] "GET /static/js/1.b3a9922d.chunk.js HTTP/1.1" 304 0 "http://192.168.1.189:8000/app/servers/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "-"
nginx_1     | 192.168.1.111 - - [28/Jan/2021:01:26:18 +0000] "GET /static/js/7.83a760e0.chunk.js HTTP/1.1" 304 0 "http://192.168.1.189:8000/app/servers/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "-"
nginx_1     | 192.168.1.111 - - [28/Jan/2021:01:26:18 +0000] "GET /static/js/12.d499cca5.chunk.js HTTP/1.1" 304 0 "http://192.168.1.189:8000/app/servers/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "-"
nginx_1     | 192.168.1.111 - - [28/Jan/2021:01:26:18 +0000] "GET /static/js/0.da4c9520.chunk.js HTTP/1.1" 304 0 "http://192.168.1.189:8000/app/servers/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "-"
nginx_1     | 192.168.1.111 - - [28/Jan/2021:01:26:18 +0000] "GET /static/js/8.0042e93f.chunk.js HTTP/1.1" 304 0 "http://192.168.1.189:8000/app/servers/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "-"
postgres_1  | 2021-01-28 01:26:18.932 UTC [8640] FATAL:  sorry, too many clients already
backend_1   | INFO:     192.168.224.4:53366 - "GET /api/v1/users/me HTTP/1.0" 500 Internal Server Error
nginx_1     | 192.168.1.111 - - [28/Jan/2021:01:26:18 +0000] "GET /api/v1/users/me HTTP/1.1" 500 21 "http://192.168.1.189:8000/app/servers/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "-"
backend_1   | ERROR:    Exception in ASGI application
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
backend_1   |     result = await app(self.scope, self.receive, self.send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
backend_1   |     return await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
backend_1   |     await super().__call__(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
backend_1   |     await self.middleware_stack(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend_1   |     raise exc from None
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend_1   |     await self.app(scope, receive, _send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
backend_1   |     response = await self.dispatch_func(request, self.call_next)
backend_1   |   File "/app/app/main.py", line 70, in db_session_middleware
backend_1   |     response = await call_next(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
backend_1   |     task.result()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
backend_1   |     response = await self.dispatch_func(request, self.call_next)
backend_1   |   File "/app/app/main.py", line 64, in sentry_exception
backend_1   |     raise e
backend_1   |   File "/app/app/main.py", line 56, in sentry_exception
backend_1   |     response = await call_next(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
backend_1   |     task.result()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
backend_1   |     raise exc from None
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
backend_1   |     await self.app(scope, receive, sender)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
backend_1   |     await route.handle(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
backend_1   |     response = await func(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 172, in app
backend_1   |     solved_result = await solve_dependencies(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 518, in solve_dependencies
backend_1   |     solved_result = await solve_dependencies(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 550, in solve_dependencies
backend_1   |     solved = await call(**sub_values)
backend_1   |   File "/app/app/core/auth.py", line 31, in get_current_user
backend_1   |     user = get_user_by_email(db, token_data.email)
backend_1   |   File "/app/app/db/crud/user.py", line 33, in get_user_by_email
backend_1   |     return db.query(User).filter(User.email == email).first()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3402, in first
backend_1   |     ret = list(self[0:1])
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
backend_1   |     return list(res)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
backend_1   |     return self._execute_and_instances(context)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3529, in _execute_and_instances
backend_1   |     conn = self._get_bind_args(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3544, in _get_bind_args
backend_1   |     return fn(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3523, in _connection_from_session
backend_1   |     conn = self.session.connection(**kw)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1138, in connection
backend_1   |     return self._connection_for_bind(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1146, in _connection_for_bind
backend_1   |     return self.transaction._connection_for_bind(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
backend_1   |     conn = bind._contextual_connect()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2304, in _contextual_connect
backend_1   |     self._wrap_pool_connect(self.pool.connect, None),
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2341, in _wrap_pool_connect
backend_1   |     Connection._handle_dbapi_exception_noconnection(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
backend_1   |     util.raise_(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
backend_1   |     raise exception
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
backend_1   |     return fn()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
backend_1   |     return _ConnectionFairy._checkout(self)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
backend_1   |     fairy = _ConnectionRecord.checkout(pool)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
backend_1   |     rec = pool._do_get()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
backend_1   |     self._dec_overflow()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
backend_1   |     compat.raise_(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
backend_1   |     raise exception
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
backend_1   |     return self._create_connection()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
backend_1   |     return _ConnectionRecord(self)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
backend_1   |     self.__connect(first_connect_check=True)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
backend_1   |     pool.logger.debug("Error on connect(): %s", e)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
backend_1   |     compat.raise_(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
backend_1   |     raise exception
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
backend_1   |     connection = pool._invoke_creator(self)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
backend_1   |     return dialect.connect(*cargs, **cparams)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
backend_1   |     return self.dbapi.connect(*cargs, **cparams)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
backend_1   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
backend_1   | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  sorry, too many clients already
backend_1   | 
backend_1   | (Background on this error at: http://sqlalche.me/e/13/e3q8)
postgres_1  | 2021-01-28 01:26:18.976 UTC [8641] FATAL:  sorry, too many clients already
backend_1   | INFO:     192.168.224.4:53370 - "GET /api/v1/servers/1/ports HTTP/1.0" 500 Internal Server Error
nginx_1     | 192.168.1.111 - - [28/Jan/2021:01:26:18 +0000] "GET /api/v1/servers/1/ports HTTP/1.1" 500 21 "http://192.168.1.189:8000/app/servers/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "-"
backend_1   | ERROR:    Exception in ASGI application
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
backend_1   |     result = await app(self.scope, self.receive, self.send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
backend_1   |     return await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
backend_1   |     await super().__call__(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
backend_1   |     await self.middleware_stack(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend_1   |     raise exc from None
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend_1   |     await self.app(scope, receive, _send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
backend_1   |     response = await self.dispatch_func(request, self.call_next)
backend_1   |   File "/app/app/main.py", line 70, in db_session_middleware
backend_1   |     response = await call_next(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
backend_1   |     task.result()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
backend_1   |     response = await self.dispatch_func(request, self.call_next)
backend_1   |   File "/app/app/main.py", line 64, in sentry_exception
backend_1   |     raise e
backend_1   |   File "/app/app/main.py", line 56, in sentry_exception
backend_1   |     response = await call_next(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
backend_1   |     task.result()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
backend_1   |     raise exc from None
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
backend_1   |     await self.app(scope, receive, sender)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
backend_1   |     await route.handle(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
backend_1   |     response = await func(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 172, in app
backend_1   |     solved_result = await solve_dependencies(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 518, in solve_dependencies
backend_1   |     solved_result = await solve_dependencies(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 550, in solve_dependencies
backend_1   |     solved = await call(**sub_values)
backend_1   |   File "/app/app/core/auth.py", line 31, in get_current_user
backend_1   |     user = get_user_by_email(db, token_data.email)
backend_1   |   File "/app/app/db/crud/user.py", line 33, in get_user_by_email
backend_1   |     return db.query(User).filter(User.email == email).first()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3402, in first
backend_1   |     ret = list(self[0:1])
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
backend_1   |     return list(res)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
backend_1   |     return self._execute_and_instances(context)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3529, in _execute_and_instances
backend_1   |     conn = self._get_bind_args(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3544, in _get_bind_args
backend_1   |     return fn(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3523, in _connection_from_session
backend_1   |     conn = self.session.connection(**kw)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1138, in connection
backend_1   |     return self._connection_for_bind(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1146, in _connection_for_bind
backend_1   |     return self.transaction._connection_for_bind(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
backend_1   |     conn = bind._contextual_connect()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2304, in _contextual_connect
backend_1   |     self._wrap_pool_connect(self.pool.connect, None),
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2341, in _wrap_pool_connect
backend_1   |     Connection._handle_dbapi_exception_noconnection(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
backend_1   |     util.raise_(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
backend_1   |     raise exception
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
backend_1   |     return fn()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
backend_1   |     return _ConnectionFairy._checkout(self)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
backend_1   |     fairy = _ConnectionRecord.checkout(pool)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
backend_1   |     rec = pool._do_get()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
backend_1   |     self._dec_overflow()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
backend_1   |     compat.raise_(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
backend_1   |     raise exception
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
backend_1   |     return self._create_connection()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
backend_1   |     return _ConnectionRecord(self)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
backend_1   |     self.__connect(first_connect_check=True)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
backend_1   |     pool.logger.debug("Error on connect(): %s", e)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
backend_1   |     compat.raise_(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
backend_1   |     raise exception
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
backend_1   |     connection = pool._invoke_creator(self)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
backend_1   |     return dialect.connect(*cargs, **cparams)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
backend_1   |     return self.dbapi.connect(*cargs, **cparams)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
backend_1   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
backend_1   | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  sorry, too many clients already
backend_1   | 
backend_1   | (Background on this error at: http://sqlalche.me/e/13/e3q8)

临时解决方法：
docker-compose restart

**Comment by LeiShi1313** [comment]
现在是有这个问题。等下个版本我优化下

**Comment by LeiShi1313** [comment]
测试版新版已经修复了这个问题，可以等测试版稳定后正式版更新即可解决
