### ISSUE TITLE
增加代理验证需求

### ISSUE THREAD

**Issue by eeokee** [Aurora-Admin-Panel/deploy#11]
非常感谢作者提供的管理面板，该面板功能强大，希望能越做越好。现有如下需求不知可否满足，欢迎讨论。

场景描述：
因为网络或其他因素，有时代理服务器无法访问，需要能代理验证是否可用，以及若不可用则发出通知

功能描述：
1.代理验证
可以配置验证频率，验证地址，返回值，超时时间等参数

2.代理验证结果展示
提供验证结果展示页面，该页面包含，验证成功/失败次数，平均响应速度，全部验证代理的结果集汇总

3.通知预警
可配置邮件、或webhook类通知方式，关联代理验证结果

**Comment by LeiShi1313** [comment]
大部分代理客户端都会集成代理检测功能。面板只会保证代理进程在线，不会验证代理的联通性
