### ISSUE TITLE
手贱点击SSH状态后就变成了这样

### ISSUE THREAD

**Issue by man2018** [Aurora-Admin-Panel/deploy#27]
我点击了SSH状态
![image](https://user-images.githubusercontent.com/18020785/147843379-94e08fcb-993f-4437-9653-e9d03e7ef4bd.png)
然后就提示下面的错误了，但转发还能用，有办法解决吗
STDOUT
Identity added: /app/ansible/priv_data_dirs/2/artifacts/c2e89ac3-e52e-47c3-80b3-ce83ca43c02a/ssh_key_data (/app/ansible/priv_data_dirs/2/artifacts/c2e89ac3-e52e-47c3-80b3-ce83ca43c02a/ssh_key_data)

PLAY [Add iptables port forward rule] ******************************************

TASK [setup] *******************************************************************

[WARNING]: Unhandled error in Python interpreter discovery for host

64.64.225.xx: Failed to connect to the host via ssh: Warning: Permanently added

'[64.64.225.xx]:65432' (ECDSA) to the list of known hosts. root@64.64.225.xx:

Permission denied (publickey,password).

fatal: [64.64.225.xx]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"64.64.225.xx\". Make sure this host can be reached over ssh: Warning: Permanently added '[64.64.225.xx]:65432' (ECDSA) to the list of known hosts.\r\nroot@64.64.225.74: Permission denied (publickey,password).\r\n", "unreachable": true}

PLAY RECAP *********************************************************************

64.64.225.xx : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0

**Comment by smartcatboy** [comment]
已在最新版本中修复，建议更新测试一下。

**Comment by smartcatboy** [comment]
这个是因为ssh连接错误造成的，请检查面板服务器能否通过ssh连接到中转机器，另外无限转圈问题已在新版本修复，请更新。
