### ISSUE TITLE
安装过程 添加管理账号    密码无法输入

### ISSUE THREAD

**Issue by qwr6868** [Aurora-Admin-Panel/deploy#44]
安装过程 添加管理账号    密码无法输入

**Comment by AMydw** [comment]
只是你看不见而已，实际上输入了…    小bug

**Comment by smartcatboy** [comment]
你好，请问可以把无法输入的情况截图示意一下吗？方便下个版本修复改进。

**Comment by smartcatboy** [comment]
你好，这是为了保证输入密码不直接显示在屏幕上，并非bug。

**Comment by qwr6868** [comment]
⠿ Network aurora_default       Created                                                      0.1s
 ⠿ Volume "aurora_db-data"      Created                                                      0.0s
 ⠿ Volume "aurora_app-data"     Created                                                      0.0s
 ⠿ Container aurora-postgres-1  Started                                                      2.1s
 ⠿ Container aurora-redis-1     Started                                                      2.1s
 ⠿ Container aurora-backend-1   Started                                                      2.5s
 ⠿ Container aurora-worker-1    Started                                                      2.5s
 ⠿ Container aurora-nginx-1     Started                                                      3.3s
Creating superuser
请输入管理员邮箱：qwr6868@qq.com
请输入密码：
请再次输入密码：

上面这2个密码位置 输入不显示

**Comment by qwr6868** [comment]
CentOS 7安装完后 添加端口 然后添加转发方式之后 网页失联了 打不开了

**Comment by smartcatboy** [comment]
> CentOS 7安装完后， 添加端口 ，然后添加转发方式之后 ，网页失联了， 打不开了 ，

你好，请使用一键脚本查看前端和后端的日志，并附上错误日志及问题截图进行排查定位。

**Comment by qwr6868** [comment]
aurora-backend-1  | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
aurora-backend-1  | INFO  [alembic.runtime.migration] Will assume transactional DDL.
aurora-backend-1  | INFO:     Started server process [10]
aurora-backend-1  | INFO:     Waiting for application startup.
aurora-backend-1  | INFO:     Application startup complete.
aurora-backend-1  | INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
aurora-backend-1  | INFO:     172.18.0.6:42168 - "POST /api/token HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42172 - "GET /api/v1/users/me HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42174 - "GET /api/v1/users/me HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42176 - "GET /api/v2/servers?page=0&size=20 HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42178 - "GET /api/v1/users/me HTTP/1.0" 200 OK
aurora-backend-1  | Sending ansible_hosts_runner task
aurora-backend-1  | Sending server.server_runner task
aurora-backend-1  | INFO:     172.18.0.6:42226 - "POST /api/v1/servers HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42228 - "GET /api/v2/servers?page=0&size=20 HTTP/1.0" 200 OK
aurora-backend-1  | Sending server.connect_runner task
aurora-backend-1  | INFO:     172.18.0.6:42230 - "POST /api/v1/servers/1/connect HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42232 - "GET /api/v1/servers/1 HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42234 - "GET /api/v2/servers/1/detailed HTTP/1.0" 200 OK
aurora-backend-1  | Sending ansible_hosts_runner task
aurora-backend-1  | Sending server.server_runner task
aurora-backend-1  | INFO:     172.18.0.6:42236 - "PUT /api/v1/servers/1 HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42238 - "GET /api/v2/servers?page=0&size=20 HTTP/1.0" 200 OK
aurora-backend-1  | Sending server.connect_runner task
aurora-backend-1  | INFO:     172.18.0.6:42240 - "POST /api/v1/servers/1/connect HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42244 - "GET /api/v1/servers/1 HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42246 - "GET /api/v2/servers/1/detailed HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42276 - "GET /api/v1/servers/1 HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42278 - "PUT /api/v1/servers/1/config HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42280 - "PUT /api/v1/servers/1/config HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42282 - "PUT /api/v1/servers/1/config HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42284 - "PUT /api/v1/servers/1/config HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42286 - "PUT /api/v1/servers/1/config HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42288 - "PUT /api/v1/servers/1/config HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42300 - "GET /api/v2/servers/1 HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42302 - "GET /api/v2/servers/1/ports?page=0&size=10 HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42304 - "POST /api/v1/servers/1/ports HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42306 - "POST /api/v1/servers/1/ports HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42308 - "POST /api/v1/servers/1/ports HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42310 - "POST /api/v1/servers/1/ports HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42312 - "POST /api/v1/servers/1/ports HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42314 - "POST /api/v1/servers/1/ports HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42316 - "POST /api/v1/servers/1/ports HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42322 - "POST /api/v1/servers/1/ports HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42324 - "POST /api/v1/servers/1/ports HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42326 - "POST /api/v1/servers/1/ports HTTP/1.0" 200 OK
aurora-backend-1  | INFO:     172.18.0.6:42328 - "GET /api/v2/servers/1/ports?page=0&size=10 HTTP/1.0" 200 OK
aurora-backend-1  | Received forward rule: {'port_id': 1, 'id': 1, 'status': 'starting', 'config': {'type': 'TCP', 'remote_ip': None, 'remote_address': '217.23.12.80', 'remote_port': 10000}, 'is_active': True, 'method': 'iptables'}
aurora-backend-1  | Sending iptables_runner task, kwargs: {'port_id': 1, 'server_id': 1, 'local_port': 10001, 'update_status': True, 'remote_address': '217.23.12.80', 'remote_port': 10000, 'forward_type': 'TCP'}
aurora-backend-1  | INFO:     172.18.0.6:42330 - "POST /api/v1/servers/1/ports/1/forward_rule HTTP/1.0" 200 OK
aurora-worker-1   | to connect to the host via ssh: ssh: Could not resolve hostname
aurora-worker-1   | http://103.206.20.62/: Name or service not known
aurora-worker-1   | fatal: [cn2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname http://103.206.20.62/: Name or service not known", "unreachable": true}
aurora-worker-1   | fatal: [cn2]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"http://103.206.20.62/\". Make sure this host can be reached over ssh: ssh: Could not resolve hostname http://103.206.20.62/: Name or service not known\r\n", "unreachable": true}
aurora-worker-1   | 
aurora-worker-1   | PLAY RECAP *********************************************************************
aurora-worker-1   | cn2                        : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
aurora-worker-1   | 
aurora-worker-1   | 
aurora-worker-1   | PLAY RECAP *********************************************************************
aurora-worker-1   | cn2                        : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
aurora-worker-1   | 
aurora-worker-1   | [2022-02-24 05:07:38,609] INFO:huey:Worker-5:tasks.server.connect_runner: acc66e3e-3d8a-4337-8fef-a1f94615aa54 p=3 executed in 2.241s
aurora-worker-1   | [2022-02-24 05:07:38,622] INFO:huey:Worker-4:tasks.server.server_runner: 618f5ac6-81d8-4dd3-b898-a485359b684c p=3 executed in 2.825s
aurora-worker-1   | [2022-02-24 05:07:44,994] INFO:huey:Worker-16:Executing tasks.ansible.ansible_hosts_runner: fc2d094f-4e64-426e-a7ec-611214a65d1f p=10
aurora-worker-1   | [2022-02-24 05:07:44,997] INFO:huey:Worker-2:Executing tasks.server.server_runner: 7ee5f3e9-3cbf-4057-ab97-4b9ebc0f9b07 p=3
aurora-worker-1   | [2022-02-24 05:07:45,008] INFO:huey:Worker-16:tasks.ansible.ansible_hosts_runner: fc2d094f-4e64-426e-a7ec-611214a65d1f p=10 executed in 0.013s
aurora-worker-1   | [2022-02-24 05:07:45,561] INFO:huey:Worker-4:Executing tasks.server.connect_runner: 43d6f367-12e3-4c79-8a34-474710219d77 p=3
aurora-worker-1   | SSH password: 
aurora-worker-1   | 
aurora-worker-1   | PLAY [cn2] *********************************************************************
aurora-worker-1   | 
aurora-worker-1   | TASK [server_init : Exec init script remotely] *********************************
aurora-worker-1   | SSH password: 
aurora-worker-1   | 
aurora-worker-1   | PLAY [Connect server] **********************************************************
aurora-worker-1   | 
aurora-worker-1   | TASK [get_facts : Get facts] ***************************************************
aurora-worker-1   | ok: [cn2]
aurora-worker-1   | 
aurora-worker-1   | TASK [get_facts : Get service facts] *******************************************
aurora-worker-1   | ok: [cn2]
aurora-worker-1   | 
aurora-worker-1   | PLAY RECAP *********************************************************************
aurora-worker-1   | cn2                        : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
aurora-worker-1   | 
aurora-worker-1   | [2022-02-24 05:08:02,899] INFO:huey:Worker-4:tasks.server.connect_runner: 43d6f367-12e3-4c79-8a34-474710219d77 p=3 executed in 17.338s
aurora-worker-1   | [2022-02-24 05:08:09,897] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task tasks.clean.clean_expired_port_runner: aa811ed1-94da-416b-9731-16a0ef67b2b2 p=4.
aurora-worker-1   | [2022-02-24 05:08:09,899] INFO:huey:Worker-4:Executing tasks.clean.clean_expired_port_runner: aa811ed1-94da-416b-9731-16a0ef67b2b2 p=4
aurora-worker-1   | [2022-02-24 05:08:09,905] INFO:huey:Worker-4:tasks.clean.clean_expired_port_runner: aa811ed1-94da-416b-9731-16a0ef67b2b2 p=4 executed in 0.007s
aurora-worker-1   | changed: [cn2]
aurora-worker-1   | 
aurora-worker-1   | TASK [services_prepare : Create aurora directory] ******************************
aurora-worker-1   | skipping: [cn2]
aurora-worker-1   | 
aurora-worker-1   | TASK [services_prepare : Sync template.service] ********************************
aurora-worker-1   | skipping: [cn2]
aurora-worker-1   | 
aurora-worker-1   | TASK [scripts_sync : Sync iptables.sh] *****************************************
aurora-worker-1   | skipping: [cn2]
aurora-worker-1   | 
aurora-worker-1   | TASK [scripts_sync : Sync tc.sh] ***********************************************
aurora-worker-1   | skipping: [cn2]
aurora-worker-1   | 
aurora-worker-1   | TASK [get_facts : Get facts] ***************************************************
aurora-worker-1   | ok: [cn2]
aurora-worker-1   | 
aurora-worker-1   | TASK [get_facts : Get service facts] *******************************************
aurora-worker-1   | ok: [cn2]
aurora-worker-1   | 
aurora-worker-1   | PLAY RECAP *********************************************************************
aurora-worker-1   | cn2                        : ok=3    changed=1    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0   
aurora-worker-1   | 
aurora-worker-1   | [2022-02-24 05:08:24,224] INFO:huey:Worker-2:tasks.server.server_runner: 7ee5f3e9-3cbf-4057-ab97-4b9ebc0f9b07 p=3 executed in 39.226s
aurora-worker-1   | [2022-02-24 05:09:09,898] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task tasks.clean.clean_expired_port_runner: 33394169-1de1-4d84-ae43-ddc2c7bf6f59 p=4.
aurora-worker-1   | [2022-02-24 05:09:09,900] INFO:huey:Worker-5:Executing tasks.clean.clean_expired_port_runner: 33394169-1de1-4d84-ae43-ddc2c7bf6f59 p=4
aurora-worker-1   | [2022-02-24 05:09:09,909] INFO:huey:Worker-5:tasks.clean.clean_expired_port_runner: 33394169-1de1-4d84-ae43-ddc2c7bf6f59 p=4 executed in 0.010s
aurora-worker-1   | [2022-02-24 05:10:09,898] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task tasks.clean.clean_expired_port_runner: 3b4eeb80-47e0-4bb4-a53b-1c6675a2dbf5 p=4.
aurora-worker-1   | [2022-02-24 05:10:09,900] INFO:huey:Worker-11:Executing tasks.clean.clean_expired_port_runner: 3b4eeb80-47e0-4bb4-a53b-1c6675a2dbf5 p=4
aurora-worker-1   | [2022-02-24 05:10:09,912] INFO:huey:Worker-11:tasks.clean.clean_expired_port_runner: 3b4eeb80-47e0-4bb4-a53b-1c6675a2dbf5 p=4 executed in 0.012s
aurora-worker-1   | [2022-02-24 05:11:09,897] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task tasks.clean.clean_expired_port_runner: 8264fc26-b703-46da-815c-19932b18be88 p=4.
aurora-worker-1   | [2022-02-24 05:11:09,899] INFO:huey:Worker-2:Executing tasks.clean.clean_expired_port_runner: 8264fc26-b703-46da-815c-19932b18be88 p=4
aurora-worker-1   | [2022-02-24 05:11:09,910] INFO:huey:Worker-2:tasks.clean.clean_expired_port_runner: 8264fc26-b703-46da-815c-19932b18be88 p=4 executed in 0.010s
aurora-worker-1   | [2022-02-24 05:12:05,965] INFO:huey:Worker-4:Executing tasks.iptables.iptables_runner: 2d580523-8674-4075-b928-709c7d66db96 p=4
aurora-worker-1   | SSH password: 
aurora-worker-1   | 
aurora-worker-1   | PLAY [Add iptables port forward rule] ******************************************
aurora-worker-1   | 
aurora-worker-1   | TASK [iptables : Sync iptables.sh] *********************************************
aurora-worker-1   | changed: [cn2]
aurora-worker-1   | 
aurora-worker-1   | TASK [iptables : Exec iptables script locally] *********************************
aurora-worker-1   | changed: [cn2]
aurora-worker-1   | 
aurora-worker-1   | TASK [iptables : Set traffic result] *******************************************
aurora-worker-1   | ok: [cn2]
aurora-worker-1   | 
aurora-worker-1   | PLAY RECAP *********************************************************************
aurora-worker-1   | cn2                        : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
aurora-worker-1   | 
aurora-worker-1   | [2022-02-24 05:12:08,922] INFO:huey:Worker-4:tasks.iptables.iptables_runner: 2d580523-8674-4075-b928-709c7d66db96 p=4 executed in 2.957s
aurora-worker-1   | [2022-02-24 05:12:09,897] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task tasks.clean.clean_expired_port_runner: 1dfbdc4f-5fa9-44cf-84a4-c8c10360e0bf p=4.
aurora-worker-1   | [2022-02-24 05:12:09,899] INFO:huey:Worker-4:Executing tasks.clean.clean_expired_port_runner: 1dfbdc4f-5fa9-44cf-84a4-c8c10360e0bf p=4
aurora-worker-1   | [2022-02-24 05:12:09,914] INFO:huey:Worker-4:tasks.clean.clean_expired_port_runner: 1dfbdc4f-5fa9-44cf-84a4-c8c10360e0bf p=4 executed in 0.015s
aurora-worker-1   | [2022-02-24 05:13:09,898] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task tasks.clean.clean_expired_port_runner: 0e742908-8272-4cb4-b40a-2556ac806cac p=4.
aurora-worker-1   | [2022-02-24 05:13:09,900] INFO:huey:Worker-5:Executing tasks.clean.clean_expired_port_runner: 0e742908-8272-4cb4-b40a-2556ac806cac p=4
aurora-worker-1   | [2022-02-24 05:13:09,915] INFO:huey:Worker-5:tasks.clean.clean_expired_port_runner: 0e742908-8272-4cb4-b40a-2556ac806cac p=4 executed in 0.016s
aurora-worker-1   | [2022-02-24 05:14:09,897] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task tasks.clean.clean_expired_port_runner: a7142c87-9b3c-48c5-8d87-fbab69c504fe p=4.
aurora-worker-1   | [2022-02-24 05:14:09,899] INFO:huey:Worker-14:Executing tasks.clean.clean_expired_port_runner: a7142c87-9b3c-48c5-8d87-fbab69c504fe p=4
aurora-worker-1   | [2022-02-24 05:14:09,915] INFO:huey:Worker-14:tasks.clean.clean_expired_port_runner: a7142c87-9b3c-48c5-8d87-fbab69c504fe p=4 executed in 0.015s

**Comment by qwr6868** [comment]
[+] Running 4/5
 ⠿ Container aurora-redis-1     Started                                                      4.2s
 ⠿ Container aurora-postgres-1  Started                                                      4.1s
 ⠿ Container aurora-backend-1   Started                                                     13.5s
 ⠿ Container aurora-worker-1    Started                                                     13.5s
 ⠋ Container aurora-nginx-1     Restarting                                                   2.0s
Error response from daemon: Cannot restart container 14c08a6f5e55f4c6f61a6d3ebaa6a08fd403ed8f75ec6c3b0d787d984a829a53: driver failed programming external connectivity on endpoint aurora-nginx-1 (360535133e1618032bbe739c862e459a724bc63c531970b71b20821626ffdcd5):  (iptables failed: iptables --wait -t filter -A DOCKER ! -i br-19d8b8fbadae -o br-19d8b8fbadae -p tcp -d 172.18.0.6 --dport 80 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1))
[错误] 重启失败！
