### ISSUE TITLE
极光面板安装失败

### ISSUE THREAD

**Issue by j650825-3k** [Aurora-Admin-Panel/deploy#51]
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.worker value 'enable_ipv6' does not match any of the regexes: '^x-'
networks.worker.ipam.config value Additional properties are not allowed ('gateway' was unexpected)
[错误] 极光面板安装失败！

Centos/Debian/Ubuntu 都安裝不了 
 /etc/docker/daemon.json 開啟 ipv6也不行

**Comment by j650825-3k** [comment]
亂搞搞好了

**Comment by aiastia** [comment]
我也碰到了 怎么解决啊

**Comment by izardi** [comment]
我也碰到了怎么解决啊

**Comment by j650825-3k** [comment]
更新 Docker compose 至少 1.29.2以上應該就好

> 我也碰到了怎么解决啊
