### ISSUE TITLE
下载gost太慢了

### ISSUE THREAD

**Issue by eeokee** [Aurora-Admin-Panel/deploy#9]
问题：
下载gost走的是网络，因为github墙的厉害，所以太慢了
![image](https://user-images.githubusercontent.com/3079825/105325209-4d84b000-5c07-11eb-887b-3f0a088c0945.png)

建议：
1. 直接打包到aurora项目中，部署时直接从项目目录复制
2. 支持自定义配置下载地址

**Comment by LeiShi1313** [comment]
建议面板部署在国外的服务器，现在的逻辑是面板机会下载各种程序，然后传到被控机上。

**Comment by eeokee** [comment]
@LeiShi1313 现在的逻辑是每次都会下载，能否调整成下载一次后缓存到面板机，如果有缓存就不再下载

**Comment by eeokee** [comment]
还是谢谢了，我直接改源码了

**Comment by LeiShi1313** [comment]
> @LeiShi1313 现在的逻辑是每次都会下载，能否调整成下载一次后缓存到面板机，如果有缓存就不再下载

不是，现在的逻辑是每台机子只会下载一次，每次都下载应该是bug
