### ISSUE TITLE
[需求]面板前端增加对HTTPS的支持（SSL证书相关设置）

### ISSUE THREAD

**Issue by juilletVent** [Aurora-Admin-Panel/deploy#91]
## 需求场景

同域名下其他端口部署了HTTPS服务，访问过这些服务后再访问极光面板的HTTP服务，Chrome系的浏览器会自动带入TLS信息，强制使用HTTPS进行访问，手动修改访问协议都没用。

## 需求（弱需求）

能否增加面板对HTTPS的部署支撑能力？只是优化体验。

如果加入开发计划，可以赞助你喝一杯咖啡哟~🥰🥰🥰

**Comment by LeiShi1313** [comment]
一般情况下都是用Nginx或者Caddy之类的反代就可以了，没必要在服务端加上https支持
